services:
  - name: my-nodejs-app
    build:
      command: |  # Use the pipe (|) for multi-line commands
        npm install
        npx pm2 kill
        npx pm2 reset all
        npx pm2 start ecosystem.config.js --no-daemon
    deploy: # or start
      command: npm start
    runtime: nodejs
    instanceType: starter
    env: production
    region: auto
    git:
      branch: master
