services:
  - name: my-nodejs-app
    type: web
    runtime: node
    plan: starter
    buildCommand: |
      npm install
      npx pm2 kill
      npx pm2 reset all
      npx pm2 start ecosystem.config.js --no-daemon
    startCommand: npm start
    region: auto
    git:
      branch: master
