services:
  - name: test-service
    type: web
    runtime: node
    plan: free
    startCommand: npm start
    buildCommand: npm install
    region: oregon
    repo: https://github.com/your-username/your-repo.git
    branch: master
