services:
  - name: test-service
    type: web
    runtime: node
    plan: free
    startCommand: npm start
    buildCommand: npm install
    region: oregon
    repo: https://github.com/ziphatech/zipha_demo_bot.git
    branch: master
