services:
  - name: my-nodejs-app
    build:
      command: npm install && npm run build # Your normal build process
    deploy: # or start
      command: npx pm2 start ecosystem.config.js --no-daemon # Start with pm2
    runtime: nodejs
    instanceType: starter
    env: production
    region: auto
    git:
      branch: master
