services:
  - name: my-nodejs-app  # REPLACE with your app's name
    build:
      command: npm install && npm run build  # REPLACE with your build command (if any)
    deploy: # or start
      command: npm start  # REPLACE with your start command
    runtime: nodejs # or your nodejs version like nodejs16
    instanceType: starter # Choose the appropriate instance type
    env: production # or development
    region: auto # or your preferred region
    git:
      branch: master # or your main branch name
