---
services:
  - name: my-nodejs-app
    build:
      command: npm install && npm run build
    deploy:
      command: npm start
    runtime: nodejs
    instanceType: starter
    env: production
    region: auto
    git:
      branch: master
